### ISSUE TITLE
Config not consisted with gameplay

### ISSUE THREAD

**Issue by VanilaBOI** [Electric131/IsThisTheWayICame#4]
So I've done more testing and am now more confused then ever. I've tested three different combinations of configs and none of the outcomes seem intended.(I was testing this all on Experimentation)
I also made sure that there is always at least one mimic present by setting the the "ZeroMimics" Weight to 0 and also checking if there was one available(there always was)

Fake Chance: 100 / Change on Use: false / Change on Use: 100
The Door was not linked to a Mimic and I checked there was at least one available.

Fake Chance: 100 / Change on Use: true / Change on Use: 100
The Door first sent me to the normal exit and when I went in and out again it was a Mimic. Granted this seems correct in a way but when I went back through the main entrance and through the fire exit it didn't chance even after mutable repeats(I tested this setting on two different runs and the result was both the same).

Fake Chance: 0 / Change on Use: true / Change on Use: 100
The Door also was linked to the normal one but never changed. This might be intended but I think the "Change on Use" should still apply here.

**Comment by Electric131** [comment]
To the third one, change on use is only a chance to _reroll_. If the chance in rerolling is 0, that's that. As for the other two, I suspect some weirdness with initial rerolls if that is the case.

**Comment by Electric131** [comment]
This is a confirmed bug, and will be fixed in the next update. Sorry for the delay.

**Comment by VanilaBOI** [comment]
Great to hear 😁
