### ISSUE TITLE
Broken if Custom Moons / Custom Bunker

### ISSUE THREAD

**Issue by DHStyle541** [Electric131/IsThisTheWayICame#7]
Hi, this is Mods make Conflict with Custom Moons and Custom Bunker if so many Fire Exit. 
You will Teleported to Different FireExit

Example:
You From Main Entrance > Teleported to FE 2 > FE 1 Inside > FE 2 Outside > FE 1 Inside > Main Entrance Inside > FE1 Outside

I hope you fix for Custom Moons and Custom Bunker
or Suggest make Disabled Teleported if you landed on Custom Moon and enter to Custom Bunker

**Comment by Electric131** [comment]
One of the features is to randomize real exits too, so I'm not sure if this is a bug or not.

**Comment by DHStyle541** [comment]
This is a bug caused by your mod.
I've tried many times

Months that I use: Orion, Infernis, Aquatis, Egypt (because this month there is a lot of FireExit, that's why I use it)

and Bunker: Scoopys Variety Mod (I set it to March to test whether it was a bug or not. and sure enough it was a bug when installing "IsThisTheWayICame" when removing "IsThisTheWayICame" the normal fire exit didn't teleport incorrectly)

So when entering via FireExit1 > FireExit2 Inside > MainEntrance > FireExit 1 Outside > FireExit2 Outside > FireExit Inside

like that over and over again. (don't try to land just once, you need to land several times to know if it's buggy or not)

I wouldn't report this if there wasn't a problem. but this actually becomes a problem and I like this mod to the point that it traumatizes my friend with FireExit

**Comment by Electric131** [comment]
I still don't quite understand the reproduction steps with your explanation of fire exit teleports. Like I said, the mod does have a feature where a real exit can teleport you to a different real exit inside.

**Comment by DHStyle541** [comment]
It's really hard to explain when using google translate, and I know what your mod is like, but please do as I say.

where it is possible to Teleport almost 100% to various places.
From the Main Entrance suddenly teleport to FireExit, then if you enter via Fireexit 1 Inside, move to FireExit 2 Inside, not OUTSIDE.

yeah, I'm tired of explaining :/

**Comment by Electric131** [comment]
My mod does not modify the teleport locations of the main entrance at all?

**Comment by DHStyle541** [comment]
nvm dude. i hope somebody can explain what i said :))))))))))
